# Generated by Django 6.0.5 on 2026-05-11 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DrillParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ATTENDED', 'Attended'), ('MISSED', 'Missed')], default='PENDING', max_length=20)),
                ('completion_notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SafetyDrill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drill_type', models.CharField(choices=[('FIRE', 'Fire Drill'), ('EVACUATION', 'Evacuation'), ('MEDICAL', 'Medical Emergency')], max_length=50)),
                ('scheduled_date', models.DateField()),
            ],
        ),
    ]
